### ISSUE TITLE
(urls.txt), POST and multipart/form-data

### ISSUE THREAD

**Issue by flddr** [JoeDog/siege#144]
I tried using POST in `urls.txt`, but it does not work:

```bash
(uri)/upload POST < path/to/file
```
and several things like this. Whereas GET works.

But i got no uploaded File.

Besides i tried:

```bash
me@u1:~$ siege -T "multipart/form-data;boundary=123456" "http://127.0.0.1:9501/upload POST < /home/me/testfile1.jpg" -g
```

but this gives:

```bash
IS ASCII: FALSE
POST /upload.html HTTP/1.0
Host: 127.0.0.1:9501
Accept: */*
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (pc-x86_64-linux-gnu) Siege/4.0.4
Connection: close
Content-type: image/jpeg
Content-length: 3201
```

I do not get the headers / upload anyway as `Content-type: multipart/form-data;boundary=123456`

I tried several files and commands 😕 

So, how to upload `multipart/form-data` and all in all several uploads (more than one file), and lastly via `urls.txt`, too?

**Comment by flddr** [comment]
Hmm

`siege --version` gives `4.0.4`, installed via `apt` on ubuntu 18.04.1

Corrected release is `4.0.4` _rc3_

I will check this at home

**Comment by flddr** [comment]
no response

**Comment by SaeedArisha** [comment]
@

> no response

Were you able to find somthing?

**Comment by muayyad-alsadi** [comment]
> So, why does https://github.com/JoeDog/siege/issues/139 work and mine not?

you error is

```
ValueError: boundary missed for Content-Type: multipart/form-data                                                      │
```

his version works because the boundary is part of his data file

```
------123456
Content-Disposition: form-data; name="result"

result-data
------123456--
```
