### ISSUE TITLE
[error] unable to set close control sock.c:141: Invalid argument

### ISSUE THREAD

**Issue by caibojun** [JoeDog/siege#149]
the error raised when I run`$ siege -c1 -r1 www.baidu.com`， as you see，I get the information as below：

> ** SIEGE 4.0.4

> **Preparing 1 concurrent users for battle.

> The server is now under siege...[error] unable to set close control sock.c:141: Invalid argument

> [error] unable to set close control sock.c:141: Invalid argument

> [error] unable to set close control sock.c:141: Invalid argument

> [error] unable to set close control sock.c:141: Invalid argument

> [error] unable to set close control sock.c:141: Invalid argument

> [error] unable to set close control sock.c:141: Invalid argument

> [error] unable to set close control sock.c:141: Invalid argument

> [error] unable to set close control sock.c:141: Invalid argument

**Comment by kennyqqr** [comment]
Same message on my centos.
Do I need to install some dependencies for it?

OS version: CentOS Linux release 7.6.1810 (Core)
Siege version: 4.0.2

**Comment by mrodal** [comment]
Im getting the same on WSL

**Comment by JoeDog** [comment]
I'm not having an issue with that site above:

mintty screen dump

lccns344 $ siege -c1 -r1 www.baidu.com
                                                 ** SIEGE 4.0.4rc3

                           ** Preparing 1 concurrent users for battle.

     The server is now under siege...
                                                      HTTP/1.1 200
1.67 secs:  153024 bytes ==> GET  /
                                HTTP/1.1 200     0.32 secs:    1131
bytes ==> GET  /baidu.html?from=noscript
             HTTP/1.1 200     0.33 secs:      91 bytes ==> GET
/img/gs.gif
HTTP/1.1 200     0.81 secs:   15629 bytes ==> GET
/5eN1bjq8AAUYm2zgoY3K/r/www/cache/bdorz/baidu.min.css
HTTP/1.1 200     2.78 secs:   93750 bytes ==> GET
/r/www/cache/static/jquery/jquery-1.10.2.min_65682a2.js
HTTP/1.1 200     0.31 secs:    6511 bytes ==> GET
/img/baidu_resultlogo@2.png
HTTP/1.1 200     0.37 secs:     705 bytes ==> GET
/img/baidu_jgylogo3.gif
HTTP/1.1 200     0.30 secs:    7877 bytes ==> GET
/img/bd_logo1.png?qua=high
HTTP/1.1 200     0.32 secs:    7877 bytes ==> GET  /img/bd_logo1.png


                           Transactions:                      9 hits

     Availability:                 100.00 %
                                                      Elapsed time:
               7.23 secs
                                Data transferred:               0.27
MB
            Response time:                  0.80 secs

Transaction rate:               1.24 trans/sec
                                                 Throughput:
          0.04 MB/sec
                           Concurrency:                    1.00

     Successful transactions:           9
                                                      Failed
transactions:               0
                                          Longest transaction:
   2.78
                    Shortest transaction:           0.30


I would suggest you re-run configure and look for any dependency issues.

**Comment by qaistars** [comment]
Getting the same error

**Comment by linuxsec** [comment]
wsl? if yes, i think this is problem on wsl. i just test on my ubuntu (dual boot) and it is normal. but i got same error on wsl.

**Comment by VittorioZinno** [comment]
yes, wsl is a problem

**Comment by ephost** [comment]
I am getting the same on WSL. It seems to still work and make requests. Is that correct?

**Comment by JoeDog** [comment]
Are using software that you compiled or did you download a binary version?

**Comment by ephost** [comment]
Jeff,
If I recall correctly I downloaded Siege and compiled. 
I did have to update WSL. I am not sure if I was supposed to ever ‘apt-get  update’ WSL but it seemed the only way to get Siege working with OpenSSL. 
Joe

    	
    	

    	CEO, EPhost, Inc. rebis@ephost.com858-433-2818 x101https://www.ephost.com
    
  



On Wed, Sep 25, 2019 at 7:10 AM -0700, "Jeff Fulmer" <notifications@github.com> wrote:










Are using software that you compiled or did you download a binary version?

**Comment by pcgeek86** [comment]
I'm getting the same error on Windows Subsystem for Linux (WSL) running Ubuntu 20.04 Focal Fossa. Seems like requests are still going through, however.

**Comment by shrutijha-ms** [comment]
Was this error issue resolved on wsl? I am still getting it on running siege on wsl (version 1).

**Comment by JoeDog** [comment]
Probably not. I have no way of debugging this environment
