### ISSUE TITLE
Output statistics in JSON format

### ISSUE THREAD

**Issue by icamys** [JoeDog/siege#151]
It would be nice if there would be an option to output statistics into JSON format in order to use the program results by another programs without writing any parsing code.

**Comment by japzio** [comment]
nice to have :-)

**Comment by bbakersmith** [comment]
This feature is now in master as `--json-output` CLI option and `json_output` config file option. I believe this issue can be closed.

**Comment by japzio** [comment]
awesome @bbakersmith @JoeDog @icamys
