### ISSUE TITLE
No details infos are showed with --verbose option

### ISSUE THREAD

**Issue by puppyapple** [JoeDog/siege#174]
Command using: 
`siege -c 120 -r 1 -v  --content-type "application/json" 'http://xxxxx POST <../siege_test.json'`

Result from command line: 
{	"transactions":			         120,
	"availability":			      100.00,
	"elapsed_time":			        3.30,
	"data_transferred":		        0.01,
	"response_time":		        1.73,
	"transaction_rate":		       36.36,
	"throughput":			        0.00,
	"concurrency":			       63.01,
	"successful_transactions":	         120,
	"failed_transactions":		           0,
	"longest_transaction":		        3.30,
	"shortest_transaction":		        0.22
}

Neither '-v' or '--verbose' gives any details of the transactions. Anyone has met the same issue?

**Comment by JoeDog** [comment]
Make sure you have 'json_output = false' in your .siege/siege.conf file 

When json_output is true, all verbosity is forced off.

**Comment by puppyapple** [comment]
> 
> 
> Make sure you have 'json_output = false' in your .siege/siege.conf file
> 
> When json_output is true, all verbosity is forced off.

@JoeDog Oh yes, thanks for the reply. I didn't noticed this configuration in .conf. The transactions information shows normally now after set it to false. Thanks again!
