### ISSUE TITLE
Query about siege

### ISSUE THREAD

**Issue by abu7elo** [JoeDog/siege#193]
Hi All,

I just want to ask a question related to siege. Does it use for hacking? Or is it a tool that can help anyone to hack my website?

Thanks,

**Comment by nask0** [comment]
Short answer: no, this tool has nothing to do with "hacking".

**Comment by abu7elo** [comment]
Thanks, who can confirm that to me in order to make sure that?

Is there any reference that mentioned it is not used for hacking?

**Comment by nask0** [comment]
This tool simply makes HTTP requests, nothing more, nothing less.
There is no way that the author can guarantee that someone will not spam your URL with HTTP requests, but this has nothing to do with hacking at all.
For that matter one can write simple bash (or actually whatever script/program) that makes HTTP requests.
I really cannot understand how HTTP requests has something to do with "hacking".
And for reference, one can read the docs or check the source code :)

**Comment by abu7elo** [comment]
Thanks again @nask0 

I really appreciate your help.

I just want to know how I can get a official confirmation that this tool does not do any hacking? Is there any specific email that I can send or anyone here can advise?

**Comment by JoeDog** [comment]
Don't hack people.
