### ISSUE TITLE
make failure on centos

### ISSUE THREAD

**Issue by Martin404** [JoeDog/siege#32]
The same question with the url :https://github.com/JoeDog/siege/issues/14,the error info follow:

Making all in lib
make[1]: Entering directory `/root/siege/lib'
Making all in joedog
make[2]: Entering directory `/root/siege/lib/joedog'
/bin/sh ../../libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../include   -I/usr/include/openssl -I/usr/include -W -Wall -Wunused-value -g -O2 -c -o memory.lo memory.c
../../libtool: line 466: CDPATH: command not found
../../libtool: line 1144: func_opt_split: command not found
libtool: Version mismatch error.  This is libtool 2.2.6b, but the
libtool: definition of this LT_INIT comes from an older release.
libtool: You should recreate aclocal.m4 with macros from libtool 2.2.6b
libtool: and run autoconf again.
make[2]: *** [memory.lo] Error 63
make[2]: Leaving directory `/root/siege/lib/joedog'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/siege/lib'
make: *** [all-recursive] Error 1

**Comment by JoeDog** [comment]
Could you try building from the source distribution:

http://download.joedog.org/siege/siege-3.1.2.tar.gz

(It has all the autotools built already)

**Comment by Martin404** [comment]
tks very much!
