### ISSUE TITLE
Support for CloudFlare SSL (TLS)

### ISSUE THREAD

**Issue by jesucarr** [JoeDog/siege#35]
When trying to benchmark my https:// site with CloudFlare activated, I get this error:

[error] Failed to make an SSL connection

It works fine using the browser.

When disabling CloudFlare it works as expected (with a self signed SSL certificate), and also it works fine with other SSL sites.

I think it is related to CloudFlare's certificate requiring TLS for the connection, rather than SSLv3.

I guess Siege needs an option to specify the protocol to use?

**Comment by JoeDog** [comment]
What version are you using? The latest works with cloudflare.  Here's
joedog.org which is fronted by cloudflare:

 $ siege -g https://www.joedog.org/
HEAD / HTTP/1.0
Host: www.joedog.org
Accept: */*
User-Agent: Mozilla/5.0 (unknown-x86_64-linux-gnu) Siege/3.1.3
Connection: close


HTTP/1.1 200 OK
Server: cloudflare-nginx
Date: Tue, 20 Oct 2015 17:09:10 GMT
Content-Type: text/html; charset=UTF-8
Connection: close
Set-Cookie: __cfduid=d92279b14285ca4e43670cd83a05e85fd1445360950;
expires=Wed, 19-Oct-16 17:09:10 GMT; path=/; domain=.joedog.org; HttpOnly
Vary: Accept-Encoding,Cookie
X-Powered-By: PHP/5.4.16
Cache-Control: max-age=3, must-revalidate
WP-Super-Cache: Served supercache file from PHP
CF-RAY: 23865434d26c0880-IAD


If you're version of openssl doesn't support TLS, then siege won't.

Jeff

**Comment by jesucarr** [comment]
First I used the one from brew: 3.1.0. I have OpenSSL 1.0.2d. 

openssl version
OpenSSL 1.0.2d 9 Jul 2015

Doing:

siege -g https://www.joedog.org/
[error] socket: 65175552 connection refused.: Connection refused
[done]

Then I installed Siege 3.1.3 with this configuration:

./configure --prefix=/Users/j/Downloads/siege-3.1.3/files --bindir=/Users/j/Downloads/siege-3.1.3/bin --mandir=/Users/j/Downloads/siege-3.1.3/man --with-ssl=/usr/local/Cellar/openssl/1.0.2d_1/bin/

And doing:

./bin/siege -g https://www.joedog.org/
[error] stack: 14077410 : error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
[error] Failed to make an SSL connection: 5
[done]

Is there anything I'm missing?

**Comment by JoeDog** [comment]
Support was added in version 3.1.1; the latest version is 3.1.2  You can
find it here:

http://download.joedog.org/siege/

**Comment by jesucarr** [comment]
I also tried with version 3.1.2 and this config:

./configure --prefix=/Users/j/Downloads/siege-3.1.2/files --bindir=/Users/j/Downloads/siege-3.1.2/bin --mandir=/Users/j/Downloads/siege-3.1.2/man --with-ssl=/usr/local/Cellar/openssl/1.0.2d_1/bin/

but same result as with version 3.1.3

**Comment by JoeDog** [comment]
What version of openssl are you using?

**Comment by jesucarr** [comment]
openssl version
OpenSSL 1.0.2d 9 Jul 2015

**Comment by JoeDog** [comment]
That should work. There must be something in your environment that's
throwing off the configure script. If it doesn't find TLS support, it
doesn't use it. What platform are you on?

**Comment by jesucarr** [comment]
I'm on OS X 10.10.5 and installed OpenSSL with brew. This is my config and make output. Do you see something wrong?

    Jesuss-MacBook-Pro:siege-3.1.2 j$ ./configure --prefix=/Users/j/Downloads/siege-3.1.2/files --bindir=/Users/j/Downloads/siege-3.1.2/bin --mandir=/Users/j/Downloads/siege-3.1.2/man --with-ssl=/usr/local/Cellar/openssl/1.0.2d_1 
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... utils/install-sh -c -d
    checking for gawk... no
    checking for mawk... no
    checking for nawk... no
    checking for awk... awk
    checking whether make sets $(MAKE)... yes
    checking build system type... x86_64-apple-darwin14.5.0
    checking host system type... x86_64-apple-darwin14.5.0
    checking for style of include used by make... GNU
    checking for gcc... gcc
    checking for C compiler default output file name... a.out
    checking whether the C compiler works... yes
    checking whether we are cross compiling... no
    checking for suffix of executables... 
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking dependency style of gcc... none
    checking how to run the C preprocessor... gcc -E
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking minix/config.h usability... no
    checking minix/config.h presence... no
    checking for minix/config.h... no
    checking whether it is safe to define __EXTENSIONS__... yes
    checking for gcc... (cached) gcc
    checking whether we are using the GNU C compiler... (cached) yes
    checking whether gcc accepts -g... (cached) yes
    checking for gcc option to accept ISO C89... (cached) none needed
    checking dependency style of gcc... (cached) none
    checking for a sed that does not truncate output... /usr/bin/sed
    checking for ld used by gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
    checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
    checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
    checking for BSD-compatible nm... /usr/bin/nm
    checking whether ln -s works... yes
    checking how to recognise dependent libraries... pass_all
    checking dlfcn.h usability... yes
    checking dlfcn.h presence... yes
    checking for dlfcn.h... yes
    checking for g++... g++
    checking whether we are using the GNU C++ compiler... yes
    checking whether g++ accepts -g... yes
    checking dependency style of g++... none
    checking how to run the C++ preprocessor... g++ -E
    checking for g77... no
    checking for xlf... no
    checking for f77... no
    checking for frt... no
    checking for pgf77... no
    checking for cf77... no
    checking for fort77... no
    checking for fl32... no
    checking for af77... no
    checking for xlf90... no
    checking for f90... no
    checking for pgf90... no
    checking for pghpf... no
    checking for epcf90... no
    checking for gfortran... gfortran
    checking whether we are using the GNU Fortran 77 compiler... yes
    checking whether gfortran accepts -g... yes
    checking the maximum length of command line arguments... 196608
    checking command to parse /usr/bin/nm output from gcc object... rm: conftest.dSYM: is a directory
    ok
    checking for objdir... .libs
    checking for ar... ar
    checking for ranlib... ranlib
    checking for strip... strip
    rm: conftest.dSYM: is a directory
    rm: conftest.dSYM: is a directory
    checking if gcc supports -fno-rtti -fno-exceptions... rm: conftest.dSYM: is a directory
    yes
    checking for gcc option to produce PIC... -fno-common
    checking if gcc PIC flag -fno-common works... rm: conftest.dSYM: is a directory
    yes
    checking if gcc static flag -static works... rm: conftest.dSYM: is a directory
    no
    checking if gcc supports -c -o file.o... rm: conftest.dSYM: is a directory
    yes
    checking whether the gcc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
    checking dynamic linker characteristics... darwin14.5.0 dyld
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... yes
    configure: creating libtool
    appending configuration tag "CXX" to libtool
    rm: conftest.dSYM: is a directory
    rm: conftest.dSYM: is a directory
    checking for ld used by g++... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
    checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
    checking whether the g++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
    checking for g++ option to produce PIC... -fno-common
    checking if g++ PIC flag -fno-common works... rm: conftest.dSYM: is a directory
    yes
    checking if g++ static flag -static works... rm: conftest.dSYM: is a directory
    no
    checking if g++ supports -c -o file.o... rm: conftest.dSYM: is a directory
    yes
    checking whether the g++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
    checking dynamic linker characteristics... darwin14.5.0 dyld
    checking how to hardcode library paths into programs... immediate
    appending configuration tag "F77" to libtool
    rm: conftest.dSYM: is a directory
    rm: conftest.dSYM: is a directory
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... yes
    checking for gfortran option to produce PIC... -fno-common
    checking if gfortran PIC flag -fno-common works... rm: conftest.dSYM: is a directory
    yes
    checking if gfortran static flag -static works... rm: conftest.dSYM: is a directory
    no
    checking if gfortran supports -c -o file.o... rm: conftest.dSYM: is a directory
    yes
    checking whether the gfortran linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
    checking dynamic linker characteristics... darwin14.5.0 dyld
    checking how to hardcode library paths into programs... immediate
    checking for perl... /usr/bin/perl
    checking for a POSIX-compliant shell... /bin/sh
    checking whether make sets $(MAKE)... (cached) yes
    checking for a BSD-compatible install... /usr/bin/install -c
    checking for buggy pthread mutex initializers... no
    checking for dlopen() in -ldld... no
    checking for dlopen() in -ldl... yes
    checking for random device... yes
    checking for ssl support... yes
    checking /usr/local/Cellar/openssl/1.0.2d_1/include/openssl/opensslv.h usability... yes
    checking /usr/local/Cellar/openssl/1.0.2d_1/include/openssl/opensslv.h presence... yes
    checking for /usr/local/Cellar/openssl/1.0.2d_1/include/openssl/opensslv.h... yes
    found ssl in /usr/local/Cellar/openssl/1.0.2d_1
    checking for OpenSSL version... >= 0.9.8 (appropriate flag set)
    checking for inline... inline
    checking for int8_t... yes
    checking for int16_t... yes
    checking for int32_t... yes
    checking for int64_t... yes
    checking for uint8_t... yes
    checking for uint16_t... yes
    checking for uint32_t... yes
    checking for uint64_t... yes
    checking for u_int32_t... yes
    checking for ssize_t... yes
    checking for ANSI C header files... (cached) yes
    checking for sys/wait.h that is POSIX.1 compatible... yes
    checking fcntl.h usability... yes
    checking fcntl.h presence... yes
    checking for fcntl.h... yes
    checking limits.h usability... yes
    checking limits.h presence... yes
    checking for limits.h... yes
    checking for unistd.h... (cached) yes
    checking signal.h usability... yes
    checking signal.h presence... yes
    checking for signal.h... yes
    checking sys/socket.h usability... yes
    checking sys/socket.h presence... yes
    checking for sys/socket.h... yes
    checking sys/select.h usability... yes
    checking sys/select.h presence... yes
    checking for sys/select.h... yes
    checking sys/time.h usability... yes
    checking sys/time.h presence... yes
    checking for sys/time.h... yes
    checking sys/times.h usability... yes
    checking sys/times.h presence... yes
    checking for sys/times.h... yes
    checking sys/resource.h usability... yes
    checking sys/resource.h presence... yes
    checking for sys/resource.h... yes
    checking errno.h usability... yes
    checking errno.h presence... yes
    checking for errno.h... yes
    checking arpa/inet.h usability... yes
    checking arpa/inet.h presence... yes
    checking for arpa/inet.h... yes
    checking netinet/in.h usability... yes
    checking netinet/in.h presence... yes
    checking for netinet/in.h... yes
    checking netdb.h usability... yes
    checking netdb.h presence... yes
    checking for netdb.h... yes
    checking pthread.h usability... yes
    checking pthread.h presence... yes
    checking for pthread.h... yes
    checking for string.h... (cached) yes
    checking for strings.h... (cached) yes
    checking sched.h usability... yes
    checking sched.h presence... yes
    checking for sched.h... yes
    checking openssl/e_os.h usability... no
    checking openssl/e_os.h presence... no
    checking for openssl/e_os.h... no
    checking openssl/e_os2.h usability... yes
    checking openssl/e_os2.h presence... yes
    checking for openssl/e_os2.h... yes
    checking for an ANSI C-conforming const... yes
    checking for size_t... yes
    checking whether time.h and sys/time.h may both be included... yes
    checking return type of signal handlers... void
    checking for working alloca.h... yes
    checking for alloca... yes
    checking for strchr... yes
    checking for memcpy... yes
    checking for strncpy... yes
    checking for strstr... yes
    checking for strlen... yes
    checking for strncasecmp... yes
    checking for strncmp... yes
    checking for socket... yes
    checking for gethostbyname... yes
    checking for snprintf... yes
    checking for strdup... yes
    checking for rand_r... yes
    checking for localtime_r... yes
    checking for getipnodebyname... yes
    checking for freehostent... yes
    checking for getopt_long... yes
    checking for poll... yes
    checking for socket in -lsocket... no
    checking for pthread_attr_init in -lpthread... yes
    PLATFORM: apple-x86_64-darwin14.5.0
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: creating src/Makefile
    config.status: creating doc/Makefile
    config.status: creating html/Makefile
    config.status: creating lib/Makefile
    config.status: creating lib/joedog/Makefile
    config.status: creating include/Makefile
    config.status: creating include/joedog/Makefile
    config.status: creating utils/Makefile
    config.status: creating include/config.h
    config.status: include/config.h is unchanged
    config.status: executing depfiles commands
    config.status: executing default-1 commands
    config.status: executing default-2 commands
    config.status: executing default-3 commands
    config.status: executing default-4 commands
    config.status: executing default-5 commands
    config.status: executing default-6 commands

    --------------------------------------------------------
    Configuration is complete

    Run the following commands to complete the installation:
      make 
      make install

    To upgrade an old siegerc file (optional): 
      mv ~/.siegerc.new ~/.siegerc

    For complete documentation:        http://www.joedog.org
    --------------------------------------------------------
    Jesuss-MacBook-Pro:siege-3.1.2 j$ make 
    Making all in .
    make[1]: Nothing to be done for `all-am'.
    Making all in include
    /Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
    Making all in joedog
    make[3]: Nothing to be done for `all'.
    Making all in lib
    Making all in joedog
    make[2]: Nothing to be done for `all'.
    make[2]: Nothing to be done for `all-am'.
    Making all in src
    make[1]: Nothing to be done for `all'.
    Making all in utils
    make[1]: Nothing to be done for `all'.
    Making all in doc
    make[1]: Nothing to be done for `all'.
    Making all in html
    make[1]: Nothing to be done for `all'.
    Jesuss-MacBook-Pro:siege-3.1.2 j$ make install
    Making install in .
    make[2]: Nothing to be done for `install-exec-am'.
    make[2]: Nothing to be done for `install-data-am'.
    Making install in include
    Making install in joedog
    make[3]: Nothing to be done for `install-exec-am'.
    make[3]: Nothing to be done for `install-data-am'.
    make[3]: Nothing to be done for `install-exec-am'.
    make[3]: Nothing to be done for `install-data-am'.
    Making install in lib
    Making install in joedog
    make[3]: Nothing to be done for `install-exec-am'.
    make[3]: Nothing to be done for `install-data-am'.
    make[3]: Nothing to be done for `install-exec-am'.
    make[3]: Nothing to be done for `install-data-am'.
    Making install in src
    test -z "/Users/j/Downloads/siege-3.1.2/bin" || ../utils/install-sh -c -d "/Users/j/Downloads/siege-3.1.2/bin"
      /bin/sh ../libtool   --mode=install /usr/bin/install -c siege '/Users/j/Downloads/siege-3.1.2/bin'
    /usr/bin/install -c siege /Users/j/Downloads/siege-3.1.2/bin/siege
    make[2]: Nothing to be done for `install-data-am'.
    Making install in utils
    /Applications/Xcode.app/Contents/Developer/usr/bin/make  install-exec-hook
    /bin/sh ../utils/mkinstalldirs /Users/j/Downloads/siege-3.1.2/bin
     /bin/sh ../libtool  --mode=install /usr/bin/install -c bombardment /Users/j/Downloads/siege-3.1.2/bin/bombardment
    /usr/bin/install -c bombardment /Users/j/Downloads/siege-3.1.2/bin/bombardment
     /bin/sh ../libtool  --mode=install /usr/bin/install -c siege2csv.pl /Users/j/Downloads/siege-3.1.2/bin/siege2csv.pl
    /usr/bin/install -c siege2csv.pl /Users/j/Downloads/siege-3.1.2/bin/siege2csv.pl
     /bin/sh ../libtool  --mode=install /usr/bin/install -c siege.config /Users/j/Downloads/siege-3.1.2/bin/siege.config
    /usr/bin/install -c siege.config /Users/j/Downloads/siege-3.1.2/bin/siege.config
    make[2]: Nothing to be done for `install-data-am'.
    Making install in doc
    /Applications/Xcode.app/Contents/Developer/usr/bin/make  install-exec-hook
    mkdir /Users/j/Downloads/siege-3.1.2/files/etc
    test -z "/Users/j/Downloads/siege-3.1.2/man/man1" || ../utils/install-sh -c -d "/Users/j/Downloads/siege-3.1.2/man/man1"
     /usr/bin/install -c -m 644 siege.1 siege.config.1 bombardment.1 siege2csv.1 '/Users/j/Downloads/siege-3.1.2/man/man1'
    test -z "/Users/j/Downloads/siege-3.1.2/man/man5" || ../utils/install-sh -c -d "/Users/j/Downloads/siege-3.1.2/man/man5"
     /usr/bin/install -c -m 644 urls_txt.5 '/Users/j/Downloads/siege-3.1.2/man/man5'
    test -z "/Users/j/Downloads/siege-3.1.2/man/man7" || ../utils/install-sh -c -d "/Users/j/Downloads/siege-3.1.2/man/man7"
     /usr/bin/install -c -m 644 layingsiege.7 '/Users/j/Downloads/siege-3.1.2/man/man7'
    Making install in html
    /Applications/Xcode.app/Contents/Developer/usr/bin/make  install-exec-hook
    HTML pages not installed
    make[2]: Nothing to be done for `install-data-am'.
    Jesuss-MacBook-Pro:siege-3.1.2 j$ ./bin/siege -g https://www.joedog.org/
    [error] stack: 14077410 : error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
    [error] Failed to make an SSL connection: 5
    [done]

**Comment by JoeDog** [comment]
In ssl.c go to line 137.  You're looking for this line:

#if defined(SSL_CTRL_SET_TLSEXT_HOSTNAME)

Change that whole block of code so it looks like this:

#if defined(SSL_CTRL_SET_TLSEXT_HOSTNAME)
  puts("SSL_CTRL_SET_TLSEXT_HOSTNAME");
  SSL_ctrl(C->ssl, SSL_CTRL_SET_TLSEXT_HOSTNAME, TLSEXT_NAMETYPE_host_name,
(char *)servername);
#else
  puts("WTF????????????");
#endif/*SSL_CTRL_SET_TLSEXT_HOSTNAME*/

Recompile and run this:

lccns344 $ ./siege -g https://www.joedog.org/
SSL_CTRL_SET_TLSEXT_HOSTNAME  <= IF YOU SEE THIS SSL IS OKAY
HEAD / HTTP/1.0
Host: www.joedog.org
Accept: */*
User-Agent: Mozilla/5.0 (unknown-x86_64-linux-gnu) Siege/3.1.3
Connection: close


HTTP/1.1 200 OK
Server: cloudflare-nginx
Date: Wed, 21 Oct 2015 19:10:25 GMT
Content-Type: text/html; charset=UTF-8
Connection: close
Set-Cookie: __cfduid=d2dc3c26ae956274f3b44e4cc5439e3351445454625;
expires=Thu, 20-Oct-16 19:10:25 GMT; path=/; domain=.joedog.org; HttpOnly
Vary: Accept-Encoding,Cookie
X-Powered-By: PHP/5.4.16
Cache-Control: max-age=3, must-revalidate
WP-Super-Cache: Served supercache file from PHP
CF-RAY: 238f432f8308247a-IAD

**Comment by jesucarr** [comment]
Hey this was very extrange. I added your debugs and suddenly it worked. Then I removed your debugs and recompiled, and it worked as well. Same exact command as previously posted. Maybe my old OpenSSL was cached somewhere in the system? Anyways, thanks a lot for your help!

**Comment by prahladyeri** [comment]
I'm facing this same issue on Ubuntu 16.04 LTS. Is this fixed yet, or at least has any workarounds?

**Comment by JoeDog** [comment]
I'll need more information. Siege supports SNI and it works on
www.joedog.org which is behind cloudflare:

Bully $ siege -g https://www.joedog.org/
HEAD / HTTP/1.0
Host: www.joedog.org
Accept: */*
User-Agent: Mozilla/5.0 (unknown-x86_64-linux-gnu) Siege/4.0.2
Connection: close


HTTP/1.1 200 OK
Date: Sat, 09 Jun 2018 13:12:28 GMT
Content-Type: text/html; charset=UTF-8
Connection: close
Set-Cookie: __cfduid=d6b6b7fe755ca9a1447590935e80658f21528549947;
expires=Sun, 09-Jun-19 13:12:27 GMT; path=/; domain=.joedog.org; HttpOnly
X-Powered-By: PHP/5.3.29
Link: <https://www.joedog.org/wp-json/>; rel="https://api.w.org/"
Expect-CT: max-age=604800, report-uri="
https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
*Server: cloudflare*
CF-RAY: 4283d995dbbfa3ff-PIT

**Comment by prahladyeri** [comment]
@JoeDog Thanks for the response! But when I try this with my site [www.prahladyeri.com](https://www.prahladyeri.com) (uses CloudFlare Flexi-SSL), I'm getting a blank:

```
rms@ubuntu:~$ siege -g https://www.prahladyeri.com
HEAD / HTTP/1.0
Host: www.prahladyeri.com
Accept: */*
User-Agent: Mozilla/5.0 (pc-x86_64-linux-gnu) Siege/3.0.8
Connection: close


[done]
 ```

And when I try to actually run a benchmark test, I get this error:

```
rms@ubuntu:~$ sudo siege -r 1 -c 1 https://www.prahladyeri.com
[sudo] password for rms: 
** SIEGE 3.0.8
** Preparing 1 concurrent users for battle.
The server is now under siege..      done.

Transactions:		           0 hits
Availability:		        0.00 %
Elapsed time:		        1.24 secs
Data transferred:	        0.00 MB
Response time:		        0.00 secs
Transaction rate:	        0.00 trans/sec
Throughput:		        0.00 MB/sec
Concurrency:		        0.00
Successful transactions:           0
Failed transactions:	           1
Longest transaction:	        0.00
Shortest transaction:	        0.00
 
FILE: /var/log/siege.log
You can disable this annoying message by editing
the .siegerc file in your home directory; change
the directive 'show-logfile' to false.
```

And these are the contents of `/var/log/siege.log`:

```
rms@ubuntu:~$ cat /var/log/siege.log 
      Date & Time,  Trans,  Elap Time,  Data Trans,  Resp Time,  Trans Rate,  Throughput,  Concurrent,    OKAY,   Failed
2018-06-09 15:03:18,      0,       4.51,           0,       -nan,        0.00,        0.00,        0.00,       0,      10
2018-06-09 15:03:48,      0,       0.41,           0,       -nan,        0.00,        0.00,        0.00,       0,       1
2018-06-09 15:04:36,      1,       2.40,           0,       1.40,        0.42,        0.00,        0.58,       1,       0
2018-06-09 15:04:46,      0,       1.32,           0,       -nan,        0.00,        0.00,        0.00,       0,       1
2018-06-09 18:54:52,      0,       1.24,           0,       -nan,        0.00,        0.00,        0.00,       0,       1

```

**Comment by JoeDog** [comment]
What version of OpenSSL are you using?

Bully $ openssl version
OpenSSL 1.0.2g  1 Mar 2016

Here's what I get:

Bully $ siege -g https://www.prahladyeri.com
HEAD / HTTP/1.0
Host: www.prahladyeri.com
Accept: */*
User-Agent: Mozilla/5.0 (unknown-x86_64-linux-gnu) Siege/4.0.2
Connection: close


HTTP/1.1 200 OK
Date: Sat, 09 Jun 2018 13:29:21 GMT
Content-Type: text/html; charset=UTF-8
Connection: close
Set-Cookie: __cfduid=ddb28a2779be6514bbfda9e863ca3523a1528550960;
expires=Sun, 09-Jun-19 13:29:20 GMT; path=/; domain=.prahladyeri.com;
HttpOnly
Link: <https://www.prahladyeri.com/wp-json/>; rel="https://api.w.org/"
Vary: Accept-Encoding
Via: e3
Expect-CT: max-age=604800, report-uri="
https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 4283f24e1dc1a405-PIT

**Comment by prahladyeri** [comment]
My OpenSSL version is exactly the same as yours, except it has `-fips` at the end:

OpenSSL 1.0.2g-fips  1 Mar 2016

And Ubuntu 16.04 LTS says that its already the latest version.

**Comment by prahladyeri** [comment]
But since you are able to get a response, the issue may not be with the SSL, right?

**Comment by JoeDog** [comment]
I am nearly certain the issue is with your openssl.

Make sure you have the dev libraries installed then recompile siege.

**Comment by Anonymity124** [comment]
The latest version 4.0.5 have the  same bug ，like ：
siege --no-parser -j -c5 -r5 https://www.baidu.com
[error] Failed to make an SSL connection: 5: Connection reset by peer

openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017
I'm Centos ,
wish ur reply.tks
^_^

**Comment by JoeDog** [comment]
$ siege -V
SIEGE 4.0.5

Copyright (C) 2020 by Jeffrey Fulmer, et al.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.

$ siege --no-parser -j -c5 -r5 https://www.baidu.com

{       "transactions":                           25,
        "availability":                       100.00,
        "elapsed_time":                         8.10,
        "data_transferred":                     5.68,
        "response_time":                        1.57,
        "transaction_rate":                     3.09,
        "throughput":                           0.70,
        "concurrency":                          4.84,
        "successful_transactions":                25,
        "failed_transactions":                     0,
        "longest_transaction":                  3.45,
        "shortest_transaction":                 1.01
}

Could you post the output of your config.log (from inside your source
directory)
