### ISSUE TITLE
siege/head `make` fail @ libtool mismatch

### ISSUE THREAD

**Issue by pgnd** [JoeDog/siege#48]
on linux/64

    lsb_release -rd
        Description:    openSUSE Leap 42.1 (x86_64)
        Release:        42.1
    gcc --version
        gcc (SUSE Linux) 5.3.1 20160212 [gcc-5-branch revision 233369]
    autoconf --version
        autoconf (GNU Autoconf) 2.69
    libtoolize --version
        libtoolize (GNU libtool) 2.4.6

building siege/HEAD

    git clone https://github.com/JoeDog/siege.git
    cd siege
    git log | head
        commit 6f9cdef7fa5b0d77d36273571c8b20cb3bf00583
        Author: J. Fulmer <jeff@joedog.org>
        Date:   Thu Feb 18 20:31:45 2016 -0500

            Routine update: 4.0.0-beta7

        commit 883c926f2b2c357b7d17913478a8c7f2f8f52596
        Author: J. Fulmer <jeff@joedog.org>
        Date:   Thu Feb 18 20:24:29 2016 -0500

    autoreconf -vif
    ./configure \
     --prefix=/usr/local/siege \
     --with-ssl=/usr/local/ssl \
     --with-gnu-ld

fails @ make

    make V=1
        ...
        Making all in joedog
        make[2]: Entering directory '/usr/local/src/siege/lib/joedog'
        /bin/sh ../../libtool  --tag=CC   --mode=compile /usr/bin/gcc-5 -DHAVE_CONFIG_H -I. -I../../include   -I/include/zlib -I/include -W -Wall -Wunused-value -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -fmessage-length=0 -grecord-gcc-switches -march=x86-64 -mtune=nocona -c -o memory.lo memory.c
        libtool: Version mismatch error.  This is libtool 2.4.6, but the
        libtool: definition of this LT_INIT comes from an older release.
        libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
        libtool: and run autoconf again.
        Makefile:378: recipe for target 'memory.lo' failed
        make[2]: *** [memory.lo] Error 63
        make[2]: Leaving directory '/usr/local/src/siege/lib/joedog'
        Makefile:364: recipe for target 'all-recursive' failed
        make[1]: *** [all-recursive] Error 1
        make[1]: Leaving directory '/usr/local/src/siege/lib'
        Makefile:398: recipe for target 'all-recursive' failed
        make: *** [all-recursive] Error 1

re-exec libtool macros+autoconf

    make clean
    libtoolize
    autoconf -v -f

doesn't cure

    ./configure \
     --prefix=/usr/local/siege \
     --with-ssl=/usr/local/ssl \
     --with-gnu-ld
    make V=1
        ...
        Making all in joedog
        make[2]: Entering directory '/usr/local/src/siege/lib/joedog'
        /bin/sh ../../libtool  --tag=CC   --mode=compile /usr/bin/gcc-5 -DHAVE_CONFIG_H -I. -I../../include   -I/include/zlib -I/include -W -Wall -Wunused-value -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -fmessage-length=0 -grecord-gcc-switches -march=x86-64 -mtune=nocona -c -o memory.lo memory.c
        libtool: Version mismatch error.  This is libtool 2.4.6, but the
        libtool: definition of this LT_INIT comes from an older release.
        libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6
        libtool: and run autoconf again.
        Makefile:378: recipe for target 'memory.lo' failed
        make[2]: *** [memory.lo] Error 63
        make[2]: Leaving directory '/usr/local/src/siege/lib/joedog'
        Makefile:364: recipe for target 'all-recursive' failed
        make[1]: *** [all-recursive] Error 1
        make[1]: Leaving directory '/usr/local/src/siege/lib'
        Makefile:398: recipe for target 'all-recursive' failed
        make: *** [all-recursive] Error 1

**Comment by JoeDog** [comment]
Here's the source distribution:

http://download.joedog.org/siege/beta/siege-4.0.0-beta7.tar.gz

Jeff

**Comment by pgnd** [comment]
thx, the src tarball builds fine.

what's the proper fix for tracking/building from git ?

**Comment by JoeDog** [comment]
You should be able to build autotools with:

utils/bootstrap
,/configure --args
make
make install

(You have to use the bootstrap command to build the man pages)

J.

**Comment by pgnd** [comment]
perfect,

siege --version
SIEGE 4.0.0-beta8

thanks.
