### ISSUE TITLE
Option to send Authentication automatically, instead of waiting for 401

### ISSUE THREAD

**Issue by jamshid** [JoeDog/siege#63]
Would be nice if HTTP Basic `Authorization` header were sent preemptively for all requests, to save the roundtrip after the 401. Maybe that could be an option?
```
# ~/.siege/siege.conf
login = user:password
```
Using 4.0.1, thanks.

**Comment by JoeDog** [comment]
To the best of my knowledge, siege is true to the HTTP/1.1 protocol (in
this regard). Basic authentication is challenge / response.

**Comment by jamshid** [comment]
Eh fair enough, also looks like Apache HttpClient dropped setAuthenticationPreemptive() 3.x => 4.x.
http://hc.apache.org/httpclient-3.x/authentication.html#Preemptive_Authentication
https://hc.apache.org/httpcomponents-client-ga/tutorial/html/authentication.html
