### ISSUE TITLE
[alert] Zip encoding disabled; siege requires zlib support to enable it

### ISSUE THREAD

**Issue by gdbtek** [JoeDog/siege#84]
on CentOS 7, siege --version return a warning of missing zlib suppport even I already install zlib-devel. Any idea how to resolve this warning?

```
[root@centos cookbooks]# siege --version
[alert] Zip encoding disabled; siege requires zlib support to enable it: No such file or directory
SIEGE 4.0.2

Copyright (C) 2016 by Jeffrey Fulmer, et al.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.
```

**Comment by JoeDog** [comment]
It would appear that it didn't pick up your zlib at configure time.

Does centos install it in a strange place?  Can you find zlib.h on your
system?

Run ./configure again and look for zlib in the output to see what's
happening

**Comment by gdbtek** [comment]
run config again and it solved the issue.. Thanks

**Comment by wikithink** [comment]
sudo ./configure --with-ssl="/usr/local/opt/openssl" --with-zlib="/usr/local/opt/zlib"
